### ISSUE TITLE
Find missing assets from secondary client

### ISSUE THREAD

**Issue by T1ti** [stoneharry/WoW-Map-Asset-Parser#1]
Extremly useful feature for downporting : 

-Allow to input a secondary source client (my legion client, extracted or not deosn't matter)

-All the missing assets from the 1st source(my WOTLK client) will be taken from my 2nd source instead

Which allows to easily find all the missing assets you need to downport for the map, rather than just running a 50gb legion patch

Probably make a special mode or make a new folder for missing assets, when doing this I don't want to copy existing Wrath assets and mix them with the ones I need, I only want the missing ones

**Comment by stoneharry** [comment]
(Paraphrased for my own use)

Check if the file being packaged already exists in the WoW client, if it does we can skip it. It doesn't need to be packaged in a custom MPQ.

Useful for downporting, where the data directory will contain all assets in the modern client (including ones already in the WOTLK client).

**Comment by stoneharry** [comment]
Fixed in 13de2c77e321dfa8f5601e44b58037b04b7c316a, closing.
